// convex/schema.ts
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// =============================================================================
// REUSABLE VALIDATORS
// =============================================================================

/**
 * The 5 public sentiment axes that define the "state of the world."
 * All start at 50. Range is 0-100.
 *
 * - stability: do people think things are under control?
 * - attention: is the public still watching this story?
 * - curiosity: do people want answers / are they digging deeper?
 * - corporate_blame: are people blaming the private sector?
 * - government_blame: are people blaming the government?
 *
 * These are the axes that factions are trying to push up or down.
 * They're independent-ish: you can have high attention + high stability
 * (people are watching but feel safe), or high blame on both sectors, etc.
 */
const sentimentsValidator = v.object({
  stability: v.number(),
  attention: v.number(),
  curiosity: v.number(),
  corporate_blame: v.number(),
  government_blame: v.number(),
});

/**
 * A scoring row is always 4 numbers: [low, medium, high, max]
 * These map to sentiment brackets:
 *   low = 0-25, medium = 26-50, high = 51-75, max = 76-100
 *
 * Each faction has a scoring row per sentiment. Positive numbers mean
 * "this bracket is good for us," negative means "this hurts us."
 *
 * Example — The Institute's stability row: [-3, -1, 2, 5]
 * means low stability is terrible for them, max stability is great.
 *
 * Game score = sum of points across all 5 sentiments based on
 * where each sentiment currently sits. Computed client-side, never stored.
 */
const scoringRowValidator = v.array(v.number()); // always length 4

/**
 * A quality describes one axis that an action is evaluated on.
 * When a player submits content for an action, the AI scores it
 * against each of the action's qualities.
 *
 * - name: short label shown to the player, e.g. "Catchy"
 * - description: shown to player as guidance, e.g. "Memorable,
 *   something people would repeat or screenshot"
 * - rubric: NOT shown to player. Detailed scoring instructions
 *   for the AI evaluator, e.g. "Score 1-3 if generic and forgettable.
 *   Score 7-10 if someone would screenshot this."
 */
const qualityValidator = v.object({
  name: v.string(),
  description: v.string(),
  rubric: v.string(),
});

/**
 * An action type is something a player can spend credits on.
 * There are 4 shared actions (available to everyone) and 3
 * faction-specific actions (one of which is a "special").
 *
 * - cost: credit cost (1-4)
 * - prompt: the question shown to the player, e.g. "What are you posting?"
 *   This is the main UX lever — the prompt frames the player's voice.
 * - qualities: what the AI evaluates the content against
 * - repeatable: only true for the 1-cost actions (social media, public statement).
 *   You can use these multiple times per round.
 * - is_special: the faction's big 4-cost signature move
 */
const actionTypeValidator = v.object({
  id: v.string(),
  name: v.string(),
  cost: v.number(),
  prompt: v.string(),
  qualities: v.array(qualityValidator),
  repeatable: v.boolean(),
  is_special: v.boolean(),
});

// =============================================================================
// SCHEMA
// =============================================================================

export default defineSchema({
  // ===========================================================================
  // GAMES
  // The top-level game state. One document per game session.
  // ===========================================================================
  games: defineTable({
    /**
     * The seed event that kicks off the game, e.g.
     * "A sinkhole opens in the financial district and something
     * is glowing at the bottom."
     * Generated by AI at game creation or picked from presets.
     */
    event: v.string(),

    /** How many rounds this game lasts. Default 4. */
    max_rounds: v.number(),

    /**
     * 0 = game hasn't started yet (still in lobby).
     * 1-4 = which round we're in.
     */
    current_round: v.number(),

    /**
     * The state machine phase. Flows like:
     * lobby → planning → submitting → resolving → results
     *   → planning → submitting → resolving → results  (repeat)
     *   → game_over
     *
     * - lobby: players joining, picking factions
     * - planning: players see sentiments + credits, pick which actions to take
     * - submitting: players write content for each selected action
     * - resolving: AI is crunching — no player input, big screen shows loading
     * - results: big screen shows the news cycle, sentiments animate, scores update
     * - game_over: final scores, epilogue, winner
     */
    phase: v.union(
      v.literal("lobby"),
      v.literal("planning"),
      v.literal("submitting"),
      v.literal("resolving"),
      v.literal("results"),
      v.literal("game_over"),
    ),

    /** Current public sentiment state. All start at 50. */
    sentiments: sentimentsValidator,

    /**
     * AI-generated summaries of what happened each round.
     * Fed back into the AI prompt for continuity.
     * Index 0 = round 1 summary, etc.
     */
    round_summaries: v.array(v.string()),

    /**
     * The 4 shared actions available to all factions.
     * Stored on the game so they're easy to read in one query.
     *
     * Social Media Post (1), Public Statement (1),
     * Place a Story (2), Anonymous Leak (3)
     */
    shared_actions: v.array(actionTypeValidator),
  }),

  // ===========================================================================
  // FACTIONS
  // There are always exactly 4 factions per game.
  //
  // - The Institute: academic, expert, wants boring calm
  // - Crowdswell: populist, grassroots, "just asking questions"
  // - Pinnacle Media Group: engagement-brained, clicks and views
  // - The Foundation for Public Good: EA-flavored, paternalistic, corporate
  // ===========================================================================
  factions: defineTable({
    game_id: v.id("games"),

    /** Display name, e.g. "The Institute" */
    name: v.string(),

    /**
     * Full personality description used in AI prompts.
     * Describes their voice, motivations, how they talk,
     * what kind of media they produce. This is what makes
     * the same action (e.g. "Social Media Post") come out
     * differently for each faction.
     */
    archetype: v.string(),

    /**
     * Current credit balance.
     * Starts at 8. Each round: +3 base, +1 for quality, +1 for highest impact.
     * Spent on actions (costs 1-4 each).
     */
    credits: v.number(),

    /**
     * The scoring table. For each sentiment, 4 numbers representing
     * how many game points this faction earns when that sentiment is
     * in the [low, medium, high, max] bracket.
     *
     * This IS the faction's objective — no separate "objectives" field needed.
     * Positive numbers = "we want this." Negative = "this hurts us."
     */
    scoring: v.object({
      stability: scoringRowValidator,
      attention: scoringRowValidator,
      curiosity: scoringRowValidator,
      corporate_blame: scoringRowValidator,
      government_blame: scoringRowValidator,
    }),

    /**
     * 3 faction-specific actions, ordered:
     * [0] = regular action at 2 credits
     * [1] = regular action at 3 credits
     * [2] = special action at 4 credits (is_special = true)
     */
    faction_actions: v.array(actionTypeValidator),
  }).index("by_game", ["game_id"]),

  // ===========================================================================
  // PLAYERS
  // Individual humans. Multiple players can be on one faction (they huddle
  // IRL and collaborate, but submit from one phone per faction in practice).
  // ===========================================================================
  players: defineTable({
    game_id: v.id("games"),
    faction_id: v.id("factions"),

    /** Display name, entered on join */
    name: v.string(),

    /**
     * Random ID stored in the browser (cookie or localStorage).
     * This is our auth — no login needed, Jackbox-style.
     * If you close and reopen the tab, you rejoin as the same player.
     */
    session_id: v.string(),
  })
    .index("by_game", ["game_id"])
    .index("by_faction", ["faction_id"])
    .index("by_session", ["session_id"]),

  // ===========================================================================
  // ROUNDS
  // One document per round per game. Stores the event development,
  // sentiment snapshots, and the AI-generated news cycle narrative.
  // ===========================================================================
  rounds: defineTable({
    game_id: v.id("games"),

    /** Which round (1-4) */
    number: v.number(),

    /**
     * AI-generated story beat for this round, e.g.
     * "Day 3: The glow is getting brighter. A perimeter has been established."
     * For round 1 this is just the initial event. For later rounds the AI
     * advances the "ground truth" of what's actually happening.
     */
    event_development: v.string(),

    /** Sentiment snapshot BEFORE this round's actions were applied */
    sentiment_before: sentimentsValidator,

    /**
     * Sentiment snapshot AFTER resolution.
     * Optional because it doesn't exist until the RESOLVING phase completes.
     */
    sentiment_after: v.optional(sentimentsValidator),

    /**
     * The big creative AI output — the news cycle narrative.
     * This is what goes on the big screen: headlines, chyrons, social media
     * posts, public reactions, all woven together into a story of what
     * the media landscape looked like this round.
     * Optional because it doesn't exist until resolution.
     */
    narrative: v.optional(v.string()),

    /**
     * Who earned bonus credits this round.
     * - quality: faction IDs that had at least one action score effectiveness >= 7
     * - highest_impact: the single faction with the highest total impact
     *   (impact = sum of cost * effectiveness across all their actions)
     *
     * Optional because it doesn't exist until resolution.
     */
    credit_bonuses: v.optional(
      v.object({
        quality: v.array(v.id("factions")),
        highest_impact: v.optional(v.id("factions")),
      }),
    ),
  }).index("by_game_and_number", ["game_id", "number"]),

  // ===========================================================================
  // SUBMITTED ACTIONS
  // Every action a faction takes in a round. This is the core player input.
  //
  // During PLANNING: the player picks which actions to take (document created
  // with content empty).
  // During SUBMITTING: the player writes content for each selected action.
  // During RESOLVING: the AI fills in effectiveness, quality_scores, impact.
  // ===========================================================================
  submitted_actions: defineTable({
    game_id: v.id("games"),
    round_id: v.id("rounds"),
    faction_id: v.id("factions"),

    /**
     * References an action type ID (from shared_actions or faction_actions).
     * We use a string ID rather than a table reference because action types
     * are config data embedded on the game/faction, not their own table.
     */
    action_type_id: v.string(),

    /** What the player actually typed. The creative content. */
    content: v.string(),

    /** Credit cost (copied from the action type for easy querying) */
    cost: v.number(),

    // --- Fields below are filled in during RESOLVING phase ---

    /**
     * Overall effectiveness score from 0-10.
     * This is the average (or weighted combo) of the individual quality scores.
     * Used to compute impact = cost * effectiveness.
     */
    effectiveness: v.optional(v.number()),

    /**
     * Per-quality breakdown, e.g. { "Catchy": 7, "Emotional": 5, "Short": 8 }
     * Keys are quality names, values are 0-10 scores.
     * We use v.record because different actions have different quality names.
     */
    quality_scores: v.optional(v.record(v.string(), v.number())),

    /**
     * impact = cost * effectiveness
     * Used to determine the "highest impact" credit bonus.
     * A perfectly executed 4-cost special (impact = 40) beats a
     * perfectly executed 1-cost social media post (impact = 10).
     */
    impact: v.optional(v.number()),

    /**
     * AI's reasoning for the scores. Not shown to players during the game
     * but useful for debugging and could be shown in a post-game recap.
     * e.g. "The whistleblower felt credible but the timeline didn't add up"
     */
    reasoning: v.optional(v.string()),
  })
    .index("by_round", ["round_id"])
    .index("by_round_and_faction", ["round_id", "faction_id"])
    .index("by_game", ["game_id"]),
});