/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinJoinCodeRouteImport } from './routes/join/$joinCode'
import { Route as GameGameIdHostRouteImport } from './routes/game/$gameId/host'
import { Route as GameGameIdPlayerPlayerIdRouteImport } from './routes/game/$gameId/player/$playerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinJoinCodeRoute = JoinJoinCodeRouteImport.update({
  id: '/join/$joinCode',
  path: '/join/$joinCode',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdHostRoute = GameGameIdHostRouteImport.update({
  id: '/game/$gameId/host',
  path: '/game/$gameId/host',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdPlayerPlayerIdRoute =
  GameGameIdPlayerPlayerIdRouteImport.update({
    id: '/game/$gameId/player/$playerId',
    path: '/game/$gameId/player/$playerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join/$joinCode': typeof JoinJoinCodeRoute
  '/game/$gameId/host': typeof GameGameIdHostRoute
  '/game/$gameId/player/$playerId': typeof GameGameIdPlayerPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join/$joinCode': typeof JoinJoinCodeRoute
  '/game/$gameId/host': typeof GameGameIdHostRoute
  '/game/$gameId/player/$playerId': typeof GameGameIdPlayerPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join/$joinCode': typeof JoinJoinCodeRoute
  '/game/$gameId/host': typeof GameGameIdHostRoute
  '/game/$gameId/player/$playerId': typeof GameGameIdPlayerPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join/$joinCode'
    | '/game/$gameId/host'
    | '/game/$gameId/player/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join/$joinCode'
    | '/game/$gameId/host'
    | '/game/$gameId/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/join/$joinCode'
    | '/game/$gameId/host'
    | '/game/$gameId/player/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinJoinCodeRoute: typeof JoinJoinCodeRoute
  GameGameIdHostRoute: typeof GameGameIdHostRoute
  GameGameIdPlayerPlayerIdRoute: typeof GameGameIdPlayerPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$joinCode': {
      id: '/join/$joinCode'
      path: '/join/$joinCode'
      fullPath: '/join/$joinCode'
      preLoaderRoute: typeof JoinJoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId/host': {
      id: '/game/$gameId/host'
      path: '/game/$gameId/host'
      fullPath: '/game/$gameId/host'
      preLoaderRoute: typeof GameGameIdHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId/player/$playerId': {
      id: '/game/$gameId/player/$playerId'
      path: '/game/$gameId/player/$playerId'
      fullPath: '/game/$gameId/player/$playerId'
      preLoaderRoute: typeof GameGameIdPlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinJoinCodeRoute: JoinJoinCodeRoute,
  GameGameIdHostRoute: GameGameIdHostRoute,
  GameGameIdPlayerPlayerIdRoute: GameGameIdPlayerPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
