/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinJoinCodeRouteImport } from './routes/join/$joinCode'
import { Route as GameGameIdHostRouteImport } from './routes/game/$gameId/host'
import { Route as GameGameIdPlayerPlayerIdRouteImport } from './routes/game/$gameId/player/$playerId'
import { Route as GameGameIdPlayerPlayerIdIndexRouteImport } from './routes/game/$gameId/player/$playerId.index'
import { Route as GameGameIdPlayerPlayerIdRoundVotingRouteImport } from './routes/game/$gameId/player/$playerId.round-voting'
import { Route as GameGameIdPlayerPlayerIdRoundResultsRouteImport } from './routes/game/$gameId/player/$playerId.round-results'
import { Route as GameGameIdPlayerPlayerIdRoundProcessingRouteImport } from './routes/game/$gameId/player/$playerId.round-processing'
import { Route as GameGameIdPlayerPlayerIdRoundLoadingRouteImport } from './routes/game/$gameId/player/$playerId.round-loading'
import { Route as GameGameIdPlayerPlayerIdIntroductionRouteImport } from './routes/game/$gameId/player/$playerId.introduction'
import { Route as GameGameIdPlayerPlayerIdIntermissionRouteImport } from './routes/game/$gameId/player/$playerId.intermission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinJoinCodeRoute = JoinJoinCodeRouteImport.update({
  id: '/join/$joinCode',
  path: '/join/$joinCode',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdHostRoute = GameGameIdHostRouteImport.update({
  id: '/game/$gameId/host',
  path: '/game/$gameId/host',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdPlayerPlayerIdRoute =
  GameGameIdPlayerPlayerIdRouteImport.update({
    id: '/game/$gameId/player/$playerId',
    path: '/game/$gameId/player/$playerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const GameGameIdPlayerPlayerIdIndexRoute =
  GameGameIdPlayerPlayerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GameGameIdPlayerPlayerIdRoute,
  } as any)
const GameGameIdPlayerPlayerIdRoundVotingRoute =
  GameGameIdPlayerPlayerIdRoundVotingRouteImport.update({
    id: '/round-voting',
    path: '/round-voting',
    getParentRoute: () => GameGameIdPlayerPlayerIdRoute,
  } as any)
const GameGameIdPlayerPlayerIdRoundResultsRoute =
  GameGameIdPlayerPlayerIdRoundResultsRouteImport.update({
    id: '/round-results',
    path: '/round-results',
    getParentRoute: () => GameGameIdPlayerPlayerIdRoute,
  } as any)
const GameGameIdPlayerPlayerIdRoundProcessingRoute =
  GameGameIdPlayerPlayerIdRoundProcessingRouteImport.update({
    id: '/round-processing',
    path: '/round-processing',
    getParentRoute: () => GameGameIdPlayerPlayerIdRoute,
  } as any)
const GameGameIdPlayerPlayerIdRoundLoadingRoute =
  GameGameIdPlayerPlayerIdRoundLoadingRouteImport.update({
    id: '/round-loading',
    path: '/round-loading',
    getParentRoute: () => GameGameIdPlayerPlayerIdRoute,
  } as any)
const GameGameIdPlayerPlayerIdIntroductionRoute =
  GameGameIdPlayerPlayerIdIntroductionRouteImport.update({
    id: '/introduction',
    path: '/introduction',
    getParentRoute: () => GameGameIdPlayerPlayerIdRoute,
  } as any)
const GameGameIdPlayerPlayerIdIntermissionRoute =
  GameGameIdPlayerPlayerIdIntermissionRouteImport.update({
    id: '/intermission',
    path: '/intermission',
    getParentRoute: () => GameGameIdPlayerPlayerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join/$joinCode': typeof JoinJoinCodeRoute
  '/game/$gameId/host': typeof GameGameIdHostRoute
  '/game/$gameId/player/$playerId': typeof GameGameIdPlayerPlayerIdRouteWithChildren
  '/game/$gameId/player/$playerId/intermission': typeof GameGameIdPlayerPlayerIdIntermissionRoute
  '/game/$gameId/player/$playerId/introduction': typeof GameGameIdPlayerPlayerIdIntroductionRoute
  '/game/$gameId/player/$playerId/round-loading': typeof GameGameIdPlayerPlayerIdRoundLoadingRoute
  '/game/$gameId/player/$playerId/round-processing': typeof GameGameIdPlayerPlayerIdRoundProcessingRoute
  '/game/$gameId/player/$playerId/round-results': typeof GameGameIdPlayerPlayerIdRoundResultsRoute
  '/game/$gameId/player/$playerId/round-voting': typeof GameGameIdPlayerPlayerIdRoundVotingRoute
  '/game/$gameId/player/$playerId/': typeof GameGameIdPlayerPlayerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join/$joinCode': typeof JoinJoinCodeRoute
  '/game/$gameId/host': typeof GameGameIdHostRoute
  '/game/$gameId/player/$playerId/intermission': typeof GameGameIdPlayerPlayerIdIntermissionRoute
  '/game/$gameId/player/$playerId/introduction': typeof GameGameIdPlayerPlayerIdIntroductionRoute
  '/game/$gameId/player/$playerId/round-loading': typeof GameGameIdPlayerPlayerIdRoundLoadingRoute
  '/game/$gameId/player/$playerId/round-processing': typeof GameGameIdPlayerPlayerIdRoundProcessingRoute
  '/game/$gameId/player/$playerId/round-results': typeof GameGameIdPlayerPlayerIdRoundResultsRoute
  '/game/$gameId/player/$playerId/round-voting': typeof GameGameIdPlayerPlayerIdRoundVotingRoute
  '/game/$gameId/player/$playerId': typeof GameGameIdPlayerPlayerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join/$joinCode': typeof JoinJoinCodeRoute
  '/game/$gameId/host': typeof GameGameIdHostRoute
  '/game/$gameId/player/$playerId': typeof GameGameIdPlayerPlayerIdRouteWithChildren
  '/game/$gameId/player/$playerId/intermission': typeof GameGameIdPlayerPlayerIdIntermissionRoute
  '/game/$gameId/player/$playerId/introduction': typeof GameGameIdPlayerPlayerIdIntroductionRoute
  '/game/$gameId/player/$playerId/round-loading': typeof GameGameIdPlayerPlayerIdRoundLoadingRoute
  '/game/$gameId/player/$playerId/round-processing': typeof GameGameIdPlayerPlayerIdRoundProcessingRoute
  '/game/$gameId/player/$playerId/round-results': typeof GameGameIdPlayerPlayerIdRoundResultsRoute
  '/game/$gameId/player/$playerId/round-voting': typeof GameGameIdPlayerPlayerIdRoundVotingRoute
  '/game/$gameId/player/$playerId/': typeof GameGameIdPlayerPlayerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join/$joinCode'
    | '/game/$gameId/host'
    | '/game/$gameId/player/$playerId'
    | '/game/$gameId/player/$playerId/intermission'
    | '/game/$gameId/player/$playerId/introduction'
    | '/game/$gameId/player/$playerId/round-loading'
    | '/game/$gameId/player/$playerId/round-processing'
    | '/game/$gameId/player/$playerId/round-results'
    | '/game/$gameId/player/$playerId/round-voting'
    | '/game/$gameId/player/$playerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join/$joinCode'
    | '/game/$gameId/host'
    | '/game/$gameId/player/$playerId/intermission'
    | '/game/$gameId/player/$playerId/introduction'
    | '/game/$gameId/player/$playerId/round-loading'
    | '/game/$gameId/player/$playerId/round-processing'
    | '/game/$gameId/player/$playerId/round-results'
    | '/game/$gameId/player/$playerId/round-voting'
    | '/game/$gameId/player/$playerId'
  id:
    | '__root__'
    | '/'
    | '/join/$joinCode'
    | '/game/$gameId/host'
    | '/game/$gameId/player/$playerId'
    | '/game/$gameId/player/$playerId/intermission'
    | '/game/$gameId/player/$playerId/introduction'
    | '/game/$gameId/player/$playerId/round-loading'
    | '/game/$gameId/player/$playerId/round-processing'
    | '/game/$gameId/player/$playerId/round-results'
    | '/game/$gameId/player/$playerId/round-voting'
    | '/game/$gameId/player/$playerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinJoinCodeRoute: typeof JoinJoinCodeRoute
  GameGameIdHostRoute: typeof GameGameIdHostRoute
  GameGameIdPlayerPlayerIdRoute: typeof GameGameIdPlayerPlayerIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$joinCode': {
      id: '/join/$joinCode'
      path: '/join/$joinCode'
      fullPath: '/join/$joinCode'
      preLoaderRoute: typeof JoinJoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId/host': {
      id: '/game/$gameId/host'
      path: '/game/$gameId/host'
      fullPath: '/game/$gameId/host'
      preLoaderRoute: typeof GameGameIdHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId/player/$playerId': {
      id: '/game/$gameId/player/$playerId'
      path: '/game/$gameId/player/$playerId'
      fullPath: '/game/$gameId/player/$playerId'
      preLoaderRoute: typeof GameGameIdPlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId/player/$playerId/': {
      id: '/game/$gameId/player/$playerId/'
      path: '/'
      fullPath: '/game/$gameId/player/$playerId/'
      preLoaderRoute: typeof GameGameIdPlayerPlayerIdIndexRouteImport
      parentRoute: typeof GameGameIdPlayerPlayerIdRoute
    }
    '/game/$gameId/player/$playerId/round-voting': {
      id: '/game/$gameId/player/$playerId/round-voting'
      path: '/round-voting'
      fullPath: '/game/$gameId/player/$playerId/round-voting'
      preLoaderRoute: typeof GameGameIdPlayerPlayerIdRoundVotingRouteImport
      parentRoute: typeof GameGameIdPlayerPlayerIdRoute
    }
    '/game/$gameId/player/$playerId/round-results': {
      id: '/game/$gameId/player/$playerId/round-results'
      path: '/round-results'
      fullPath: '/game/$gameId/player/$playerId/round-results'
      preLoaderRoute: typeof GameGameIdPlayerPlayerIdRoundResultsRouteImport
      parentRoute: typeof GameGameIdPlayerPlayerIdRoute
    }
    '/game/$gameId/player/$playerId/round-processing': {
      id: '/game/$gameId/player/$playerId/round-processing'
      path: '/round-processing'
      fullPath: '/game/$gameId/player/$playerId/round-processing'
      preLoaderRoute: typeof GameGameIdPlayerPlayerIdRoundProcessingRouteImport
      parentRoute: typeof GameGameIdPlayerPlayerIdRoute
    }
    '/game/$gameId/player/$playerId/round-loading': {
      id: '/game/$gameId/player/$playerId/round-loading'
      path: '/round-loading'
      fullPath: '/game/$gameId/player/$playerId/round-loading'
      preLoaderRoute: typeof GameGameIdPlayerPlayerIdRoundLoadingRouteImport
      parentRoute: typeof GameGameIdPlayerPlayerIdRoute
    }
    '/game/$gameId/player/$playerId/introduction': {
      id: '/game/$gameId/player/$playerId/introduction'
      path: '/introduction'
      fullPath: '/game/$gameId/player/$playerId/introduction'
      preLoaderRoute: typeof GameGameIdPlayerPlayerIdIntroductionRouteImport
      parentRoute: typeof GameGameIdPlayerPlayerIdRoute
    }
    '/game/$gameId/player/$playerId/intermission': {
      id: '/game/$gameId/player/$playerId/intermission'
      path: '/intermission'
      fullPath: '/game/$gameId/player/$playerId/intermission'
      preLoaderRoute: typeof GameGameIdPlayerPlayerIdIntermissionRouteImport
      parentRoute: typeof GameGameIdPlayerPlayerIdRoute
    }
  }
}

interface GameGameIdPlayerPlayerIdRouteChildren {
  GameGameIdPlayerPlayerIdIntermissionRoute: typeof GameGameIdPlayerPlayerIdIntermissionRoute
  GameGameIdPlayerPlayerIdIntroductionRoute: typeof GameGameIdPlayerPlayerIdIntroductionRoute
  GameGameIdPlayerPlayerIdRoundLoadingRoute: typeof GameGameIdPlayerPlayerIdRoundLoadingRoute
  GameGameIdPlayerPlayerIdRoundProcessingRoute: typeof GameGameIdPlayerPlayerIdRoundProcessingRoute
  GameGameIdPlayerPlayerIdRoundResultsRoute: typeof GameGameIdPlayerPlayerIdRoundResultsRoute
  GameGameIdPlayerPlayerIdRoundVotingRoute: typeof GameGameIdPlayerPlayerIdRoundVotingRoute
  GameGameIdPlayerPlayerIdIndexRoute: typeof GameGameIdPlayerPlayerIdIndexRoute
}

const GameGameIdPlayerPlayerIdRouteChildren: GameGameIdPlayerPlayerIdRouteChildren =
  {
    GameGameIdPlayerPlayerIdIntermissionRoute:
      GameGameIdPlayerPlayerIdIntermissionRoute,
    GameGameIdPlayerPlayerIdIntroductionRoute:
      GameGameIdPlayerPlayerIdIntroductionRoute,
    GameGameIdPlayerPlayerIdRoundLoadingRoute:
      GameGameIdPlayerPlayerIdRoundLoadingRoute,
    GameGameIdPlayerPlayerIdRoundProcessingRoute:
      GameGameIdPlayerPlayerIdRoundProcessingRoute,
    GameGameIdPlayerPlayerIdRoundResultsRoute:
      GameGameIdPlayerPlayerIdRoundResultsRoute,
    GameGameIdPlayerPlayerIdRoundVotingRoute:
      GameGameIdPlayerPlayerIdRoundVotingRoute,
    GameGameIdPlayerPlayerIdIndexRoute: GameGameIdPlayerPlayerIdIndexRoute,
  }

const GameGameIdPlayerPlayerIdRouteWithChildren =
  GameGameIdPlayerPlayerIdRoute._addFileChildren(
    GameGameIdPlayerPlayerIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinJoinCodeRoute: JoinJoinCodeRoute,
  GameGameIdHostRoute: GameGameIdHostRoute,
  GameGameIdPlayerPlayerIdRoute: GameGameIdPlayerPlayerIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
